[my]
  token = "some default value"
  count = 121
  mycount = 0
  mystring = ""
  stringslice = ["123", "1234"]
  Ktes = 0
  [my.Sub]
    Hello = ""
    [my.Sub.SubOfSub]
      InSub = false
    [my.Sub.PtrOfSub]
      your_name = ""
  [my.log]
    SubLog = 0
    Directory = ""
    filename = ""
    dedicatedArg = ""
