my:
  token: some default value
  count: 121
  mycount: 0
  mystring: ""
  stringslice:
    - "123"
    - "1234"
  ktes: 0
  sub:
    hello: ""
    subofsub:
      insub: false
    ptrofsub:
      your_name: ""
  log:
    sublog: 0
    directory: ""
    filename: ""
    dedicatedArg: ""
